version: 2

multi-ecosystem-groups:
  ci-dependencies:
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(deps)"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "ci-dependencies"

  - package-ecosystem: "pip"
    directory: "/scripts"
    patterns:
      - "*"
    multi-ecosystem-group: "ci-dependencies"
