/**
 * @file AcidAlgorithm.h
 * Declares deterministic stepped/sliding Acid modulation for the Electronica bank.
 *
 * @author Axel Napolitano
 * @note Original Free Modular Drift concept and Rust firmware by Quinn Freedman.
 * @copyright Copyright (C) 2026 Axel Napolitano
 * @license GPL-3.0-or-later
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
#ifndef FMD_DOMAIN_ELECTRONICA_ACID_ALGORITHM_H
#define FMD_DOMAIN_ELECTRONICA_ACID_ALGORITHM_H

#include <stdint.h>

#include "fmd/domain/Types.h"
#include "fmd/ports/ReferenceTables.h"

namespace fmd {

/**
 * @brief Deterministic 16-step level grammar with project-defined accents and slides.
 *
 * @details
 * Acid advances on the Electronica sixteenth-note grid. The underlying 16 target
 * values are generated by a fixed permutation rather than copied musical content.
 * Marked slide steps interpolate from the previous target toward the current target;
 * marked accent steps add a short decaying contribution. Texture controls both
 * effects. This is an acid-style CV contour, not a TB-303 audio emulation.
 */
class AcidAlgorithm {
 public:
  /**
   * @brief Construct Acid at step zero with the cyclic previous target preloaded.
   * @param referenceTables Long-lived provider for the Electronica tempo mapping.
   */
  explicit AcidAlgorithm(const IReferenceTables& referenceTables);

  /**
   * @brief Advance the 16-step phrase by one scheduler sample.
   * @param controls Current 10-bit control frame. Speed+CV determine grid tempo;
   *        Texture+CV determine accent and slide depth.
   * @return Saturated 12-bit modulation value in the inclusive range 0..4095.
   */
  uint16_t step(const ControlFrame& controls);

 private:
  const IReferenceTables& referenceTables_;  ///< Non-owning tempo/reference-table provider.
  uint32_t phase_;                           ///< Unsigned phase within the active sixteenth note.
  uint8_t stepIndex_;                        ///< Active 16-step phrase index, always 0..15.
  uint16_t previousTargetDac12_;             ///< Previous step's base target for slide interpolation.
  uint16_t currentTargetDac12_;              ///< Current project-defined base target before accent.
};

}  // namespace fmd
#endif  // FMD_DOMAIN_ELECTRONICA_ACID_ALGORITHM_H
