#!/usr/bin/env python3
"""Validate source-file documentation and readability conventions.

The checks intentionally stay lightweight and deterministic so they can run in
CI without requiring Doxygen itself. Doxyfile remains available for generating
API documentation locally when Doxygen is installed.
"""
from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOTS = [ROOT / "lib", ROOT / "src", ROOT / "test"]
SOURCE_SUFFIXES = {".h", ".hpp", ".cpp"}
MAX_LINE_LENGTH = 140

REQUIRED_HEADER_MARKERS = (
    "@file",
    "@author Axel Napolitano",
    "@note Original Free Modular Drift concept and Rust firmware by Quinn Freedman.",
    "@copyright Copyright (C) 2026 Axel Napolitano",
    "@license GPL-3.0-or-later",
    "SPDX-License-Identifier: GPL-3.0-or-later",
)


def source_files() -> list[Path]:
    files: list[Path] = []
    for source_root in SOURCE_ROOTS:
        files.extend(
            path
            for path in source_root.rglob("*")
            if path.is_file() and path.suffix in SOURCE_SUFFIXES
        )
    return sorted(files)


def validate_file(path: Path) -> list[str]:
    problems: list[str] = []
    text = path.read_text(encoding="utf-8")
    first_block = text[:1000]

    if not text.startswith("/**"):
        problems.append("file does not start with a Doxygen file header")

    for marker in REQUIRED_HEADER_MARKERS:
        if marker not in first_block:
            problems.append(f"missing file-header marker: {marker}")

    file_match = re.search(r"@file\s+([^\s*]+)", first_block)
    if not file_match:
        problems.append("missing @file filename")
    elif file_match.group(1) != path.name:
        problems.append(
            f"@file names {file_match.group(1)!r}, expected {path.name!r}"
        )

    for line_number, line in enumerate(text.splitlines(), start=1):
        if len(line) > MAX_LINE_LENGTH:
            problems.append(
                f"line {line_number} has {len(line)} characters; "
                f"maximum is {MAX_LINE_LENGTH}"
            )

    return problems


def validate_generated_tables() -> list[str]:
    problems: list[str] = []
    generated_dir = ROOT / "lib/fmd/include/fmd/config/generated"
    for path in sorted(generated_dir.glob("*.inc")):
        text = path.read_text(encoding="utf-8")
        if not text.startswith(
            "// Generated by scripts/generate_reference_tables.py; do not edit by hand."
        ):
            problems.append(f"{path.relative_to(ROOT)}: missing generated-file provenance")
    return problems



def validate_algorithm_api_documentation() -> list[str]:
    """Require a minimum semantic Doxygen contract for every algorithm API."""
    problems: list[str] = []
    domain_root = ROOT / "lib/fmd/include/fmd/domain"
    for path in sorted(domain_root.rglob("*Algorithm.h")):
        if path.name.endswith("AlgorithmMath.h"):
            continue
        text = path.read_text(encoding="utf-8")
        relative = path.relative_to(ROOT)
        checks = (
            (text.count("@brief") >= 3, "needs class, constructor and step @brief documentation"),
            (text.count("@param") >= 2, "needs constructor/step parameter documentation"),
            (text.count("@return") >= 1, "needs explicit step return-value documentation"),
            (text.count("///<") >= 3, "needs semantic documentation for persistent state members"),
        )
        for ok, message in checks:
            if not ok:
                problems.append(f"{relative}: {message}")
    return problems


def validate_math_api_documentation() -> list[str]:
    """Ensure bank math headers describe units/ranges through param/return docs."""
    problems: list[str] = []
    domain_root = ROOT / "lib/fmd/include/fmd/domain"
    for path in sorted(domain_root.rglob("*AlgorithmMath.h")):
        text = path.read_text(encoding="utf-8")
        relative = path.relative_to(ROOT)
        if "@param" not in text:
            problems.append(f"{relative}: mathematical API has no @param documentation")
        if "@return" not in text:
            problems.append(f"{relative}: mathematical API has no @return documentation")
    return problems


def validate_shared_clock_documentation() -> list[str]:
    """Protect the cross-bank clock contract from regressing to terse comments."""
    path = ROOT / "lib/fmd/include/fmd/domain/ClockSource.h"
    text = path.read_text(encoding="utf-8")
    problems: list[str] = []
    for marker in ("@details", "0..5 V", "@param", "@return"):
        if marker not in text:
            problems.append(f"{path.relative_to(ROOT)}: missing shared-clock contract marker {marker!r}")
    if text.count("///<") < 5:
        problems.append(f"{path.relative_to(ROOT)}: persistent clock state is insufficiently documented")
    return problems

def main() -> int:
    problems: list[str] = []
    files = source_files()

    for path in files:
        for problem in validate_file(path):
            problems.append(f"{path.relative_to(ROOT)}: {problem}")

    problems.extend(validate_generated_tables())
    problems.extend(validate_algorithm_api_documentation())
    problems.extend(validate_math_api_documentation())
    problems.extend(validate_shared_clock_documentation())

    if problems:
        for problem in problems:
            print(f"code-documentation error: {problem}", file=sys.stderr)
        return 2

    print(
        f"code documentation: {len(files)} C++/header files validated; "
        f"generated-table provenance and semantic API contracts present"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
