#!/usr/bin/env python3
"""Regenerate deterministic Drift lookup-table includes.

The exponential and gamma tables retain the original mathematical contracts.
The triangular ICDF is intentionally endpoint-complete: 257 boundary samples
cover 256 interpolation intervals, fixing the upstream final-interval plateau.
"""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1] / "lib/fmd/include/fmd/config/generated"


def write(name, values, formatter, per_line, description):
    lines = [
        "// Generated by scripts/generate_reference_tables.py; do not edit by hand.",
        f"// {description}",
    ]
    for i in range(0, len(values), per_line):
        chunk = ", ".join(formatter(v) for v in values[i : i + per_line])
        if i + per_line < len(values):
            chunk += ","
        lines.append(chunk)
    (ROOT / name).write_text("\n".join(lines) + "\n", encoding="utf-8")


def rust_round(value):
    # Rust f64::round(): halfway cases away from zero.
    return math.floor(value + 0.5) if value >= 0 else math.ceil(value - 0.5)


exp = [
    max(0, min(0xFFFFFFFF, round((2.0 ** (16.0 * i / 256.0)) * 65536.0)))
    for i in range(256)
]

# Boundary samples p=i/256 make every one of the 256 interpolation intervals
# endpoint-complete. Runtime random values still occupy [0, 1), as expected for
# a 15-bit uniform integer source.
icdf = []
for i in range(257):
    p = i / 256.0
    if p <= 0.0:
        x = -1.0
    elif p >= 1.0:
        x = 1.0
    elif p < 0.5:
        x = -1.0 + math.sqrt(2.0 * p)
    else:
        x = 1.0 - math.sqrt(2.0 * (1.0 - p))
    icdf.append(max(-32768, min(32767, rust_round(x * 32767.0))))

gamma = [
    0 if i == 0 else max(0, min(255, round(((i / 255.0) ** 2.2) * 255)))
    for i in range(256)
]

# Anchor uses a bounded triangular innovation with variance 1/6. Its discrete
# AR(1) update is x[n+1]=(1-alpha)x[n]+gain*s*z[n], where z follows that
# triangular distribution. The gain below therefore normalizes stationary
# spread approximately independently of Speed:
#   gain = sqrt(6 * (1 - (1-alpha)^2)).
# Speed is quantized in the same mapped-control domain used by the production
# exponential frequency map (8 control codes per bucket, 0..306).
def interpolate_exp2_q16_16(combined_control):
    lookup_position = combined_control * 20
    lower = lookup_position >> 8
    upper = min(255, lower + 1)
    weight = (lookup_position << 8) & 0xFFFF
    start = exp[lower]
    end = exp[upper]
    return start + (((end - start) * weight) >> 16)


def phase_increment_from_decihertz_q16_16(value):
    return ((value << 16) + 50000) // 100000


anchor_gain = []
for bucket in range(307):
    combined = min(2455, bucket * 8 + 4)
    phase_increment = phase_increment_from_decihertz_q16_16(
        interpolate_exp2_q16_16(combined)
    )
    ambient_increment = (phase_increment + 8) >> 4
    alpha = ambient_increment / float(1 << 32)
    a = 1.0 - alpha
    gain = math.sqrt(max(0.0, 6.0 * (1.0 - a * a)))
    anchor_gain.append(max(0, min(32767, round(gain * 32768.0))))

write(
    "Exp2Table.inc",
    exp,
    lambda v: f"0x{v:08X}UL",
    4,
    "256-entry base-2 exponential lookup table in unsigned Q16.16.",
)
write(
    "IcdfTable.inc",
    icdf,
    str,
    8,
    "257 endpoint-complete samples of the symmetric triangular ICDF in signed Q1.15.",
)
write(
    "GammaTable.inc",
    gamma,
    str,
    16,
    "256-entry gamma 2.2 transfer table for 8-bit LED PWM.",
)

write(
    "AnchorGainTable.inc",
    anchor_gain,
    str,
    12,
    "307 Q1.15 Anchor triangular-innovation compensation gains for 8-code Speed buckets.",
)
